<?php
/**
 * Created by PhpStorm.
 * User: 张强
 * Date: 2017/2/27
 * Time: 22:44
 */

namespace frontend\controllers;

use frontend\modules\blog\controllers\BlogController;
use frontend\modules\life\controllers\AboutMeController;
use frontend\modules\life\controllers\LifeController;
use frontend\modules\words\controllers\WordsController;
use yii\web\Controller;

class BaseController extends Controller {

	public $layout = '/main';
	public $hasTop = true;
	public $hasFoot = true;
	public $hasNav = true;
	public $words = '';
	public $title = '';
	protected $titleArr;

	public function init() {
		parent::init(); // TODO: Change the autogenerated stub
		$this->titleArr = $this->getTitleArr();;
		$this->title = isset($this->titleArr[ self::className() ]['name']) ?
			$this->titleArr[ self::className() ]['name'] : '';
	}

	public function actions() {
		return [
			'error'   => [
				'class' => 'yii\web\ErrorAction',
			],
			'captcha' => [
				'class'           => 'yii\captcha\CaptchaAction',
				'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
			],
		];
	}

	/**
	 * 首页title
	 *
	 * @return array
	 */
	protected function getTitleArr() {
		return $this->titleArr = [
			IndexController::className()   => [
				'name' => '首页',
				'english' => 'Index',
				'url'  => '/',
			],
			BlogController::className()    => [
				'name' => '博客',
				'english' => 'Blog',
				'url'  => '/blog/blog/index',
			],
			WordsController::className() => [
				'name' => '闲言碎语',
				'english' => 'Saying',
				'url'  => '/words/words/words-list',
			],
			AboutMeController::className() => [
				'name' => '关于我',
				'english' => 'AboutMe',
				'url'  => '/life/about-me/index',
			]
		];
	}
}