<?php
/**
 * Created by PhpStorm.
 * User: 张强
 * Date: 2017/2/27
 * Time: 22:44
 */

namespace frontend\controllers;

use frontend\modules\blog\controllers\BlogController;
use frontend\modules\life\controllers\AboutMeController;
use frontend\modules\words\controllers\WordsController;
use yii\web\Controller;

class BaseController extends Controller
{
    public $layout = '/main';
    public $hasTop = true;
    public $hasFoot = true;
    public $hasNav = true;
    public $words = '';
    public $title = '';
    protected $titleArr ;

    public function init()
    {
	    parent::init(); // TODO: Change the autogenerated stub
	    $this->titleArr = [
	    	IndexController::className() => '首页',
		    BlogController::className() => '博客',
		    WordsController::className() => '岁言碎语',
		    AboutMeController::className() => '关于我',
	    ];
    }

	public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }
}