<?php
/**
 * Created by PhpStorm.
 * User: 张强
 * Date: 2017/3/5
 * Time: 22:52
 */

namespace frontend\modules\words\controllers;

use frontend\controllers\BaseController;

class WordsController extends BaseController
{
	public $words = '你，生命中最重要的过客，之所以是过客，因为你未曾为我停留。';

	public function init()
	{
		parent::init(); // TODO: Change the autogenerated stub
		$this->title = $this->titleArr[ self::className() ];
	}

    public function actionWordsList()
    {
        return $this->render('wordsList');
    }

}