<?php
/**
 * Created by PhpStorm.
 * User: 张强
 * Date: 2017/3/12
 * Time: 10:50
 */

namespace frontend\modules\test\controllers;

use EasyWeChat\Factory;

class TestController extends \frontend\controllers\BaseController
{

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub
    }

    public function actionUser($type){
        $app = $this->getApp($type);

        $list = $app->user->list();

        if(empty($list['data']['openid'])){
            throw new \Exception("获取openid列表失败");
        }
        $res = $app->user->select($list['data']['openid']);
        var_dump(array_column($res['user_info_list'],'nickname','openid'));die;

//        $userInfo = [];
//        foreach ($list['data']['openid'] as $openid){
//            $app->user->select($list['data']['openid']);
//        }
    }


    /**
     * @param $type
     * @return \EasyWeChat\OfficialAccount\Application
     * @throws \Exception
     */
    private function getApp($type)
    {
        switch ($type){
            case 'aaa':
                $config= $this->getMicroWxConfig();
                break;
            default:
                throw new \Exception('未找到配置');
        }

        $app = Factory::officialAccount($config);

        return $app;
    }

    /**
     * @return array
     */
    private function getMicroWxConfig()
    {
        return [
            'debug' => true,
            'app_id' => 'wx54106dc24dbe88f0',
            'secret' => 'fc5463c7631f6a216f10e316bc598a12',
            'token' => '',
            'aes_key' => '',
            // 指定 API 调用返回结果的类型：array(default)/collection/object/raw/自定义类名
            'response_type' => 'array',

            'log' => [
                'level' => 'debug',
                'file' => \Yii::getAlias('@runtime') . '/logs/wechat.log',
            ],
        ];
    }
}